org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.vfs.watch=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official
kotlin.incremental=true
android.useAndroidX=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
